# frozen_string_literal: true

# >>> Basic Site Info
#source: "https://rubygems.org"
theme: jekyll-theme-chirpy
baseurl: ""  # If you're using GitHub Pages with a custom domain, leave this empty
lang: en

# >>> SEO
url: "https://shinhchung.github.io"
title: HongHead
tagline: Share my life
description: >-
  A minimal, responsive, and powerful Jekyll theme for presenting professional writing.

# >>> Social
social:
  name: Derek Chung
  links:
    - https://twitter.com/shinhchung
    - https://github.com/shinhchung
    - https://www.linkedin.com/in/shinhchung

# >>> GitHub and Twitter Usernames
github:
  username: shinhchung
twitter:
  username: shinhchung

# >>> Language and Time
prefer_datetime_locale:
timezone: America/New_York

# >>> Web Analytics
analytics:
  google:
    id: # e.g. G-XXXXXXX
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:

# >>> Page Views (optional)
pageviews:
  provider: # now only supports 'goatcounter'

# >>> Theme Mode (light/dark/system)
theme_mode:

# >>> CDN for images (optional)
cdn: "https://img.hnghd.com"

# >>> Avatar
avatar: /assets/img/avatar.jpg

# >>> Social preview image
social_preview_image:

# >>> Table of contents
toc: true

# >>> Comments
comments:
  provider: giscus
  giscus:
    repo: shinhchung/shinhchung.github.io
    repo_id: R_kgDOH4jM8Q
    category: Comments
    category_id: DIC_kwDOH4jM8c4CRulM
    mapping: url
    input_position: top
    lang: en
    reactions_enabled: 1

toc: true

# >>> Self-hosted Assets
assets:
  self_host:
    enabled:
    env:

# >>> PWA
pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:

# >>> Pagination
paginate: 10

# >>> Markdown / Syntax Highlighting
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# >>> Collections
collections:
  tabs:
    output: true
    sort_by: order

# >>> Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

# >>> SASS
sass:
  style: compressed

# >>> HTML Compression
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

# >>> Excludes
exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

# >>> Jekyll Archives
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
